### ISSUE TITLE
Unconfigurable Hardcoded Size Restrictions

### ISSUE THREAD

**Issue by bnbalsamo** [harvard-lts/FITSservlet#22]
The hardcoded size restrictions in [FitsServlet.java](https://github.com/harvard-lts/FITSservlet/blob/dev/src/edu/harvard/hul/ois/fits/service/servlets/FitsServlet.java) (THRESHOLD_SIZE, MAX_FILE_SIZE, MAX_REQUEST_SIZE) aren't able to be configured in any way other than recompiling the .war and restarting Tomcat, it appears.

Tomcat documents settings that would (I expect) handle this size limiting in user-accessible configuration files, Namely:

- [multipart-config in web.xml](https://tomcat.apache.org/tomcat-7.0-doc/servletapi/javax/servlet/annotation/MultipartConfig.html)
- [maxPostSize specified on Connector elements](https://tomcat.apache.org/tomcat-7.0-doc/config/ajp.html).

In my own brief testing I wasn't able to get any of these settings to have an effect on the web interface (though I am woefully inexperienced in Tomcat configuration, so it may be possible to chalk this one up to user error).

**Comment by daveneiman** [comment]
Hello,
These values will now be configurable in a new properties file that can be externalized from the WAR file. It will be available in a new release within the next couple of weeks. To preview, see the dev branch README section about catalina.properties, list item 4 [here](https://github.com/harvard-lts/FITSservlet#add-entries-to-catalinaproperties).
