### ISSUE TITLE
fits.home has not been set, invalid fits directory on windows 10

### ISSUE THREAD

**Issue by knasen88** [harvard-lts/FITSservlet#30]
https://i.imgur.com/9f1HQdZ.png
this is my error, tomcat 8.5
From what i've gathered in the "deploying to tomcat" section these are what i put in the catalina.properties in the tomcat "conf" folder
`fits.home=C:/download/fits`
`shared.loader=${fits.home}/lib/*.jar`

I'm trying to build it locally before I push it on the server but as soon as I leave localhost:8080/fits/ I recieve this error. (wether I upload a file or not, the fits main page works fine)

**Comment by daveneiman** [comment]
Not sure you should have the 'C:' in the `fits.home` property.

**Comment by knasen88** [comment]
I am running Windows 10.
removing C and having
`:/download/fits ,  /down...  and down...` yields no difference in result

**Comment by knasen88** [comment]
So i pushed it to the server and set the paths, to my surprise it worked!
I am however getting an error related to the XML.
Should I close this or not? considering the windows path is still "broken".

**Comment by daveneiman** [comment]
Yes, I'll close this. Please open another issue regarding the XML error and supply any FITS output and errors or stack traces. Thanks.
