### ISSUE TITLE
Combine FITSServlet_Container project into FITSservlet project

### ISSUE THREAD

**Issue by daveneiman** [harvard-lts/FITSservlet#37]
https://github.com/harvard-lts/FITSServlet_Container

**Comment by awoods** [comment]
This task should result in a working Dockerfile in https://github.com/harvard-lts/FITSServlet based on what is currently found in: https://github.com/harvard-lts/FITSServlet_Container

After the completion of this task, the [FITSServlet_Container](https://github.com/harvard-lts/FITSServlet_Container) GitHub repo should be archived.
